variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

stages:
  - build

build-image:
  stage: build
  image: docker:latest
  environment: Send_sms
  rules:
    - exists: 
        - Dockerfile
        - send_sms.py
  before_script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]];then
        TAG="latest"
      elif [[ $CI_COMMIT_TAG != null ]];then
        TAG="$CI_COMMIT_TAG"
      else
        TAG="$CI_COMMIT_TAG"
      fi
    - docker build --pull --no-cache -t "$CI_REGISTRY_IMAGE":"$TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$TAG"